num_cores_per_subject: 4

num_subjects_at_once: 1

output_directory: /mnt/output

working_directory: /mnt/working

write_all_outputs: False

start_idx: 0

stop_idx: None

slice_timing_correction: True

write_report: False

write_graph: True